from __future__ import annotations

from typing import Protocol

from product_content_platform.domain import Asset, Batch, BatchItemStatus, PagePlan, Project


class PlatformRepository(Protocol):
    """Persistence interface for project and batch aggregates."""

    def save_project(self, project: Project) -> None: ...

    def get_project(self, project_id: str) -> Project | None: ...

    def list_projects(self) -> list[Project]: ...

    def update_project(self, project: Project) -> None: ...

    def save_asset(self, asset: Asset, project: Project) -> None: ...

    def get_asset(self, asset_id: str) -> Asset | None: ...

    def list_assets(self, project_id: str) -> list[Asset]: ...

    def save_plan(self, plan: PagePlan, project: Project) -> None: ...

    def get_plan(self, project_id: str) -> PagePlan | None: ...

    def save_batch(self, batch: Batch, projects: list[Project]) -> None: ...

    def get_batch(self, batch_id: str) -> Batch | None: ...

    def list_batches(self) -> list[Batch]: ...

    def update_batch_item(self, batch_id: str, item_id: str, status: BatchItemStatus, error: str = "") -> Batch | None: ...

    def set_batch_status(self, batch_id: str, status: str) -> Batch | None: ...
